stages:  
    - dependencies  
    - deploy

install_dependencies_angular:  
    stage: dependencies
    before_script:    
        - cd frontend  
    script:
        - npm ci --prefer-ofline --no-audit
    artifacts:    
        paths:      
            - frontend/node_modules    
        expire_in: 1 days
    only:
        - main

deploy_backend:  
    stage: deploy  
    before_script:    
        - sudo -u www-data /bin/rm -rf /var/www/backend/*.php  
    script:    
        - sudo -u www-data /bin/cp -r backend/*.php /var/www/backend/  
    tags:    
        - chartes  
    only:    
        - main

deploy_frontend:  
    stage: deploy  
    script:
        - cd frontend
        - sudo /usr/bin/ng build
        - sudo /bin/rm -rf /var/www/frontend/*
        - sudo -u www-data /bin/cp -r frontend/* /var/www/frontend/
    tags:    
        - chartes  
    only:    
        - main

